### ISSUE TITLE
Unable to install environment from SE3nv.yml

### ISSUE THREAD

**Issue by nzrandol** [RosettaCommons/RFdiffusion#1]
First of all, thanks to the RFDiffusion team for this tool and making it open source! I'm excited to use it! 

I've begun the installation process and have tried to create the conda environment from the SE3nv.yml file with `conda env create -f env/SE3nv.yml`. But get the following error: 
```
ResolvePackageNotFound: 
  - icecream
  - cudatoolkit=11.1
```

I've resolved this issue by adding `- nvidia` to the channels and moving `icecream` to the pip installs. The final file looks like this:
```
name: SE3nv
channels:
  - defaults
  - pytorch
  - dglteam
  - nvidia
dependencies:
  - python=3.9
  - pytorch=1.9
  - torchaudio
  - torchvision
  - cudatoolkit=11.1
  - dgl-cuda11.1
  - pip
  - pip:
    - icecream
    - hydra-core
    - pyrsistent
```

Not sure if this is the best way to handle creating the environment but seems to have worked for me!

**Comment by davidcjuergens** [comment]
Okay excellent, glad you've got it working now! Thank you for sharing this, we will probably adjust the `SE3nv.yml` accordingly. I'll leave this issue open for a bit so people can see your strategy while we double check environment installation.

**Comment by davidcjuergens** [comment]
Updated the SE3nv.yml file.
