### ISSUE TITLE
Is it possible to run RFdiffusion without the GPU?

### ISSUE THREAD

**Issue by xizhesun** [RosettaCommons/RFdiffusion#105]
Dear RFdiffusion  developers，

As we don't have a GPU on our server, I wanna ask whether it is possible to run RFdiffusion without the GPU?

many thanks!

**Comment by joewatchwell** [comment]
Yes, it should run fine on cpus (this is in fact what we do when making lots of small-ish designs; we just parallelise across many cpus). If your designs are less than around 200 amino acids in total length, it should run quite quickly, although the scaling (compared to GPU) gets quite bad with longer designs
