### ISSUE TITLE
ModuleNotFoundError: No module named 'pyrsistent'

### ISSUE THREAD

**Issue by bhavranek** [RosettaCommons/RFdiffusion#109]
I am trying to use Rfdiffusion on the google collab notebook. When setting up RFdifussion (first step), I keep getting the following error: 

ModuleNotFoundError                       Traceback (most recent call last)
<timed exec> in <module>

[/content/RFdiffusion/inference/utils.py](https://localhost:8080/#) in <module>
     15 import logging
     16 import string
---> 17 from inference import model_runners
     18 import hydra
     19 import glob

1 frames
[/content/RFdiffusion/inference/symmetry.py](https://localhost:8080/#) in <module>
      1 """Helper class for handle symmetric assemblies."""
----> 2 from pyrsistent import v
      3 from scipy.spatial.transform import Rotation
      4 import functools as fn
      5 import torch

ModuleNotFoundError: No module named 'pyrsistent'

**Comment by bhavranek** [comment]
this happens during the downloading RFdiffusion params part of the setup

**Comment by sokrypton** [comment]
Thanks for the report. I'll investigate.

**Comment by sokrypton** [comment]
This should now be resolved. (close and reopen the notebook). Looks like Google Colab no longer installs pyrsistent by default.
