### ISSUE TITLE
No pAE_interaction<10

### ISSUE THREAD

**Issue by RogerLang** [RosettaCommons/RFdiffusion#113]
Hi, I am using RFdiffsion and dl_binder_design to design peptide's binder. But I didn't get any result whose pAE_interaction below 10. The minimum pAE_interaction is 10.907, and almost pAE_interaction are around 25. I've  generated 6000 backbones, and assigned sequence for each backbone.

**Comment by kenndshi** [comment]
@RogerLang can you please tell how you eventually solved the high pae_interaction problem?

**Comment by ChengkuiZhao2048** [comment]
I have the same problem, how you solve it.
