### ISSUE TITLE
How to generate a binder when using Docker

### ISSUE THREAD

**Issue by TN-bio** [RosettaCommons/RFdiffusion#114]
This github shows an execution example using Docker.

docker run -it --rm --gpus all \
  -v $HOME/models:$HOME/models \
  -v $HOME/inputs:$HOME/inputs \
  -v $HOME/outputs:$HOME/outputs \
  rfdiffusion \
  inference.output_prefix=$HOME/outputs/motifscaffolding \
  inference.model_directory_path=$HOME/models \
  inference.input_pdb=$HOME/inputs/5TPN.pdb \
  inference.num_designs=3 \
  'contigmap.contigs=[10-40/A163-181/10-40]'

This is  motif scaffolding.
Can you give me an example of using hotspot to generate a binder protein in Docker?

**Comment by kenndshi** [comment]
@TN-bio 
How have you figured out the solution? 
For example, I want to generate a 10 to 40 amino acid long binder in docker for my protein A which has 230 amino acids.
Is this command accurate?
'contingmap.contigs=[10-40/A1-230]'
