### ISSUE TITLE
Got wrong Amino Acid

### ISSUE THREAD

**Issue by ChengkuiZhao** [RosettaCommons/RFdiffusion#115]
Hello, I just run several examples in the tutorial, and got the result pdb file such as motif scaffold. It's weird that all the generated amino acid is letter "G". Any one encounter this situation. Or I guess is the model not running correctly? Here is the new generated protein.
<img width="557" alt="MotifScaffold" src="https://github.com/RosettaCommons/RFdiffusion/assets/68649404/74b28d6b-f256-4c26-918e-b30982ca0bb1">

**Comment by ChengkuiZhao** [comment]
It seems the model is not iterating during the process.
<img width="1156" alt="1693467184976" src="https://github.com/RosettaCommons/RFdiffusion/assets/68649404/99debce8-bf9d-4255-93f3-0f6adf16afe3">

**Comment by ojdoha** [comment]
I ran into same problem when used ActiveSite model
![Capture](https://github.com/RosettaCommons/RFdiffusion/assets/143678688/7a801452-e198-4073-a54a-19ea2bc0ffa9)

**Comment by roccomoretti** [comment]
RFDiffusion only generates backbone structure, it does not do sequence design.

To figure out the sidechain identities, you would have to use another program like [ProteinMPNN](https://github.com/dauparas/ProteinMPNN). (This was what was used in the main RFDiffusion paper.)

**Comment by ChengkuiZhao** [comment]
Thanks for answering! I am a freshman on protein folding.  So you mean that It's OK with this result?  And I just need to  try  ProteinMPNN then.

**Comment by roccomoretti** [comment]
If the backbone structure looks reasonable, then RFDiffusion is doing it's job. To get a non-Glycine sequence, use another method like ProteinMPNN.

**Comment by davidcjuergens** [comment]
Thank you @roccomoretti ! Closing this issue as it seems resolved. RFdiffusion gives backbone only, the glycines are just arbitrary sequence to be able to write a pdb file for viewing the RFdiffusion structure. ProteinMPNN can then be used to design a sequence for the backbone.
