### ISSUE TITLE
Why there is no inpaint_str in contigmap?

### ISSUE THREAD

**Issue by wangm23456** [RosettaCommons/RFdiffusion#124]
I noticed that there is no inpaint_str in the contig option group, but it can be parsed in contigs.py and related to diffusion_mask in the code running the model.

I'm using RFDiffusion to solve the motif-scaffolding problem.
Is this a problem?  Will this affect the generation of structures?

**Comment by joewatchwell** [comment]
Yep we hadn't previously implemented this, but because the contig code came from elsewhere, it appeared to be implemented etc. We'll fix this today
