### ISSUE TITLE
error .trb file 

### ISSUE THREAD

**Issue by wangdoc2002** [RosettaCommons/RFdiffusion#130]
Hi,

Thanks for developing the great software.
I've got a wrong .trb result after running the example unconditioning design, and my own design. This type of .trb file can not be further processed by the down stream script "dl_binder_design: addFIXEDlabels.py". The "addFIXEDlabels.py" will report an error message: "Traceback (most recent call last):
  File "/dssg/home/acct-clsljd/clsljd/bin/dl_binder_design/helper_scripts/addFIXEDlabels.py", line 34, in <module>
    last_res_id = int(data['receptor_con_hal_pdb_idx'][0][1]) - 1
KeyError: 'receptor_con_hal_pdb_idx'"

I believe this is because the .trb file is wrong.
[design_unconditional_9.trb.zip](https://github.com/RosettaCommons/RFdiffusion/files/12694261/design_unconditional_9.trb.zip)
[design_motifscaffolding_inpaintseq_0.trb.zip](https://github.com/RosettaCommons/RFdiffusion/files/12694262/design_motifscaffolding_inpaintseq_0.trb.zip)

Thanks for your help.

Wang

**Comment by Joseph-Vineland** [comment]
I am having the exact same problem.  It is preventing me from desinging the binders.

**Comment by joewatchwell** [comment]
can you send me the example command you ran? I can look into this

**Comment by wangdoc2002** [comment]
Hi Joe, and Joseph,

Thanks so much for your reply.
The RFdiffusion is great that it can also repair a non-ideal part of a protein. This was my run of the program:

../scripts/run_inference.py inference.output_prefix=example_outputs/YbtE/Arcp_C1_106-256_100/100 inference.input_pdb=input_pdbs/Arcp_C1_106-256.pdb 'contigmap.contigs=[A106-189/14/A204-256]' inference.num_designs=100 

I am aiming at fixing the majority of the protein YbtE, and let the program design a 14-residues fragment for me. 
The program runs perfectly for me, generating the required pdb and trb files.

At the moment I opend this issue thread, I thought the trb file is wrong, because it is not compatible with the downstream "addFIXEDlabels.py". But now I know that it is pickled. I asked google Bard write a python script for me to unpickle the trb file. The file name of the python script is "Unpickle.py". 
The unpickling shows these tags:
con_ref_pdb_idx 
con_hal_pdb_idx 
con_ref_idx0 
con_hal_idx0 
inpaint_str 
inpaint_seq 
sampled_mask
mask_1d 

There is no "receptor_con_hal_pdb_idx" tag.

I changed the "receptor_con_hal_pdb_idx" to "con_hal_pdb_idx". It can now run in the "addFIXEDlabels.py" script , but failed to append "Fixed" remarks at required positions. 

ChatGPT4 figured out something and rewrited the "addFIXEDlabels.py" script. The name of it is "add2.py". Now the script runs well and output new pdb files with the "Fixed" remarks.

However, when I fed the generated pdb files to "/mpnn_fr/dl_interface_design.py", it reported a "failed in 1 seconds with error: <class 'IndexError'>" and quit from run. 

At the moment, it appears to me that there will be some incompatibility beween RFdiffusion and the down stream dl_binder_design in my way of using them. 

[Unpickle.py.zip](https://github.com/RosettaCommons/RFdiffusion/files/12787447/Unpickle.py.zip)
[add2.py.zip](https://github.com/RosettaCommons/RFdiffusion/files/12787448/add2.py.zip)

**Comment by wangdoc2002** [comment]
Hi Joe

This is the script fixed by Preetham Venkatesh. It resovled the issue perfectly.
At the moment, it is not possible to design sequences for a monomer using the "dl_interface_design.py" program.
[add3.py.zip](https://github.com/RosettaCommons/RFdiffusion/files/12788046/add3.py.zip)

**Comment by joewatchwell** [comment]
great - I think Nate will push that fix to the addRMSD script in the coming few days. It's true that the dl_binder_design repo isn't set up to do monomer design. For that you'll need to just use regular ProteinMPNN.

**Comment by nrbennet** [comment]
Preetham's fix is now added to dl_binder_design. Thanks for pointing this out!
