### ISSUE TITLE
Secondary Structure Prediction for Only One PDB Chain

### ISSUE THREAD

**Issue by brystingjosephine** [RosettaCommons/RFdiffusion#131]
Hi, within the following code, I am wondering whether it is possible to select secondary structure prediction on only one chain of an input pdb? This is because pdbs often often are shown as complexes: 

./make_secstruc_adj.py --input_pdb ./2KL8.pdb --out_dir /my/dir/for/adj_secstruct

Any ideas, please let me know!

Best, 
Josephine Brysting
PhD Student @ EMBL Heidelberg

**Comment by joewatchwell** [comment]
Yep, the suggestion from LaurinLang is good - just save the chain as it's own distinct pdb, and then pipe that in!

**Comment by brystingjosephine** [comment]
Hi @LaurinLang and @joewatchwell - thank you, sure that also works!
