### ISSUE TITLE
Uninstallable in linux cluster

### ISSUE THREAD

**Issue by javarianajeeb** [RosettaCommons/RFdiffusion#134]
I am getting this error while trying to set up the environment:

Could not solve for environment specs
The following packages are incompatible
├─ cudatoolkit 11.1**  is uninstallable because it conflicts with any installable versions previously reported;
└─ pytorch 1.9**  is uninstallable because it conflicts with any installable versions previously reported.

**Comment by roccomoretti** [comment]
The default install uses Cuda 11.1. If you have/need a different Cuda version, then you'll have to adjust the installation files. (As mentioned briefly in [the installation instructions](https://github.com/RosettaCommons/RFdiffusion#conda-install-se3-transformer).) -- In particular, take a look at the [env/SE3nv.yml](https://github.com/RosettaCommons/RFdiffusion/blob/main/env/SE3nv.yml) file.
