### ISSUE TITLE
The schedule of beta when T is changing

### ISSUE THREAD

**Issue by Guo-Stone** [RosettaCommons/RFdiffusion#141]
When changing diffusion time T,  why is the beta scaled? In DDIM, when shortening the diffusion time T, they don't scale the beta. Your code is as following：
-----------------------------------Python Code----------------------------------
# Adjust b0 and bT if T is not 200
# This is a good approximation, with the beta correction below, unless T is very small
assert T >= 15, "With discrete time and T < 15, the schedule is badly approximated"
b0 *= 200 / T
bT *= 200 / T

**Comment by blt2114** [comment]
Hi @Guo-Stone,

Thanks for the good question.  We did not properly explain this in either the code or in the paper supplement.

In our initial implementation assumed a fixed number of time steps T=200, and set the sequence of beta's as in DDPM [1].  However, this can be adapted for inference with a smaller number of time steps by appealing to the continuous-time SDE perspective outlined in [2].

Specifically, `schedule`, as computed here (https://github.com/RosettaCommons/RFdiffusion/blob/820bfdfaded8c260b962dc40a3171eae316b6ce0/rfdiffusion/diffusion.py#L34)  agrees with the variables $beta_i$ in appendix C of [2], when you take $\bar \beta_{min}=b0*200$ and $\beta_{max}=bT*200$.

As described in appendix C of [2], when the number of steps (T) is large, this schedule agrees with the variance preserving SDE with $beta(t)=\bar \beta_{min} + t (\bar \beta_{max}- \bar \beta_{min}).$

But when T< 15, we find that this approximation is inaccurate, and empirically find more steps are needed.  I suspect, however, that other more clever scalings of intermediate steps could allow good inferences with perhaps still significantly fewer steps.

Does this help?

References:
[1] Denoising Diffusion Probabilistic Models https://arxiv.org/abs/2006.11239
[2] Score-Based Generative Modeling through Stochastic Differential Equations https://arxiv.org/abs/2011.13456

**Comment by sokrypton** [comment]
Easiest way to explain this:
The model was trained with 200 steps
. If you want to take less than 200 steps, then you need to take larger steps to eventually end up at th same point.

So if you take 100 steps, then your step size should be 200/100 = 2.0

**Comment by Guo-Stone** [comment]
Thanks for your easy explanation! I see~ orz
