### ISSUE TITLE
Can a binder be designed to span two or more chains of a protein complex?

### ISSUE THREAD

**Issue by akirakaren** [RosettaCommons/RFdiffusion#149]
Is there a way to design a binder that diffuses across two neighboring chains within a PDB file with the current version of RFdiffusion? If so, would there be a workflow that would be recommended? Amazing tool and thank you in advance.

**Comment by kenndshi** [comment]
You probably should use ppi.hotspot_residue to specify the exact residues that your binder should bind.
Besides that, you should correctly specify the contents for your 2 chains including chain breaks. 
Example.
'contigmap.contigs=[A1-247/0 C1-419/0 (those are 2 chains A and C of a protein complex where I specified the length of each one ) 7-40/0(with this command you can tell the diffusion how much shall your binder length be, in this case it will randomly generate binders with 7 to 40 amino acids long]'.

**Comment by akirakaren** [comment]
Thank you!
