### ISSUE TITLE
Consistently getting high pae_interaction scores

### ISSUE THREAD

**Issue by kenndshi** [RosettaCommons/RFdiffusion#151]
I am trying to generate a binder with the length of my protein-protein complex.
The expected binding pocket shall be located inside my 2 proteins. I have successfully run 1000 Rfdesigns but after running the protein mpnn and af2guess. But the initial guess gave a 27+ pae_interaction score for all my binders.
Any ideas about how can I get lower scores?
The complex itself was modeled my af2 and doesn't contain any missing residues.
P.S. I have been trying to model with the same parameters a different P-P complex and got the same issue of consistently getting pa_int>27

**Comment by akirakaren** [comment]
Hi kenndshi, 
Did you figure out how to achieve a lower pae_interaction score? If so, could you share what you did? Thanks!

**Comment by kenndshi** [comment]
> Hi kenndshi, Did you figure out how to achieve a lower pae_interaction score? If so, could you share what you did? Thanks!

Greetings.
I didn't get any response from the devs, so it's not more of an issue but it's the way that it should work.
While examining their research paper I saw that most of their pae_int scores from 10.000 designs were around 26-27 and the ~6% of them had pae_int scores less than 10. (I currently don't remember exact numbers; you can check it for yourself).
It is worth mentioning that in my case the binding pocket includes 2 separate chains, and the binder design should be harder and most likely I would get even worse scores (the calculations are still running). If your target is one protein with well-defined binding pocket, you should get better results. 
The only way to deal with it is to run more than 10k designs hoping that you will get better scores, if you are doing less than 10k it may be pointless.

**Comment by kenndshi** [comment]
@KoningCheems 
The thing is that at first I was giving as contig input the whole A, B chains. Despite the fact that I specified the hotspots, RF search will still try to design the binder in other parts of the protein which are pointless.
The way I solved it is that I found the neighboring amino acids residues of my hotspots(within 5 A) and gave as an input protein.
After it, running proteinmpnn with multiple relax cycles and seqs_per_struct gave much better results. ( In their colab version you can specify both relax_cycles and seqs_per_struct, but their GitHub code wont let you do that, you have to do it in 2 separate designs).
After that the search engine had "less" residues to design therefore 39% from my 10k design were in my desired hotspot.( Which I quickly searched for by a simple bash script)
Hope this helped

**Comment by KoningCheems** [comment]
@kenndshi 
Thanks for getting back! Glad to hear you were able to get binders. So then did you still follow trough with the alpha fold initial guess to get the pae score and other metrics? What worries me is the the target RMSD score that becomes really high in my designs (around 10~20) and I think it is because the input chains A and B are being merged into one during RFdiffusion

**Comment by kenndshi** [comment]
> @kenndshi 
> Thanks for getting back! Glad to hear you were able to get binders. So then did you still follow trough with the alpha fold initial guess to get the pae score and other metrics? What worries me is the the target RMSD score that becomes really high in my designs (around 10~20) and I think it is because the input chains A and B are being merged into one during RFdiffusion 

Can you please tell your execution code?

**Comment by kenndshi** [comment]
> @kenndshi 
> Thanks for getting back! Glad to hear you were able to get binders. So then did you still follow trough with the alpha fold initial guess to get the pae score and other metrics? What worries me is the the target RMSD score that becomes really high in my designs (around 10~20) and I think it is because the input chains A and B are being merged into one during RFdiffusion 

Besides the provided pipeline, I also run short equilibration with ambertools, after which I ran mmpbsa and gpbsa calculations and got delta G around -40 and less for some of my designs which seem quite solid.
But it is worth mentioning that I had access to multiple 4090 GPU's and 256+ CPU cores and maybe for others the short MD for 10k designs would be accessible.
