### ISSUE TITLE
Loading IGSO3 from a cache directory

### ISSUE THREAD

**Issue by nzrandol** [RosettaCommons/RFdiffusion#2]
Hello! I'm having a lot of fun playing around with this!

One feature that would be convenient to have would be a constant directory where all of the diffuser's pre-computed schedules live. Right now the inference code recomputes the schedule pkl if it doesn't exists in `./`. To avoid recomputing whenever you're running in a different directory, the constant cache directory ensures that the schedule is only computed once.

I've implemented a simple version of this by replacing line 116 in `inference/model_runners.py` with
 `self.diffuser = Diffuser(**self._conf.diffuser, cache_dir=f'{SCRIPT_DIR}/../schedules')`
  instead of 
  `self.diffuser = Diffuser(**self._conf.diffuser)`. 
  This assumes that there is a `schedules` directory in the RFdiffusion folder where all pre-computed schedules will live. Only downside to this simple approach is that the cache directory couldn't be overwritten (but this is technically consistent with the model checkpoints).

**Comment by joewatchwell** [comment]
Glad you're enjoying it! This is now implemented. Thanks for the suggestion!
Joe
