### ISSUE TITLE
CUDA backend failed to initialize

### ISSUE THREAD

**Issue by xinran1129305** [RosettaCommons/RFdiffusion#208]
CUDA backend failed to initialize: Found CUDA version 12010, but JAX was built against version 12020, which is newer. The copy of CUDA that is installed must be at least as new as the version against which JAX was built. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
running proteinMPNN...
running AlphaFold...

**Comment by xinran1129305** [comment]
How to resolve this problem? Thanks in advance.

**Comment by xinran1129305** [comment]
@sokrypton could you please help me solve this problem? Thanks :)

**Comment by itzfredz** [comment]
<img width="696" alt="Screenshot 2024-03-17 at 22 33 28" src="https://github.com/RosettaCommons/RFdiffusion/assets/132261351/f2a3ea2a-adc8-46d3-9057-802259d0f04f">

CUDA backend failed to initialize: Found CUDA version 12010, but JAX was built against version 12020, which is newer. The copy of CUDA that is installed must be at least as new as the version against which JAX was built. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.

Having this same issue as well with the "run ProteinMPNN to generate sequence and AlphaFold to validate" part of the Colab notebook.

**Comment by sokrypton** [comment]
Thanks! Still investigating, but it seems like jax and dgl were built with different cuda libraries... trying to figure out how to unify these.

**Comment by sokrypton** [comment]
I just pushed to fix. Can you try again?

**Comment by narubi2** [comment]
I had experienced same issues, but now it works well.
Thanks @sokrypton

**Comment by xinran1129305** [comment]
Thanks a lot!:) @sokrypton
