### ISSUE TITLE
Using sequence in potentials

### ISSUE THREAD

**Issue by geraseva** [RosettaCommons/RFdiffusion#259]
I am trying to make a custom potential that needs not only backbone coordinates, but also a sequence matrix. Now I am using LigandMPNN inside my potential, but it is a quite complicated way. Could sequence generated by RFDiffusion be used instead, and, if so, which functions should be rewritten to provide its use?

**Comment by roccomoretti** [comment]
RFdiffusion is primary concerned with generating backbone coordinates, not sequence identities. It would be a substantial re-write to have it generate sequence information for the newly generated residues. (Note, though, that it can take sequence information for input residues.)

If you're looking to do joint sequence/structure generation, take a look at ProteinGenerator (https://doi.org/10.1038/s41587-024-02395-w).

**Comment by geraseva** [comment]
Thank you!
