### ISSUE TITLE
About downstream sequence assignment

### ISSUE THREAD

**Issue by Lyang556** [RosettaCommons/RFdiffusion#26]
Hi, RF diffusion team

The results showed that every designed residue is output as glycine, and we should use ProteinMPNN to assign these residues.

My question is, if we want to fix some residues from the input structure (e.g., enzyme design or scaffold functional motif, I want to fix the activate site or functional motif), how to specify in ProteinMPNN? 

Thank you.

**Comment by joewatchwell** [comment]
This is done with `--fixed_positions_jsonl` in ProteinMPNN. You can make this input quite trivially, if you use the `.trb` file outputs to work out which residues were fixed during RFdiffusion (i.e. if your contig input was `50-100/A1-10/50-100` and you want to fix the identity of the residues that were `A1-10` from your `input_pdb`, you can see where they are in the output pdb by looking in `con_hal_pdb_idx` in the `.trb` file
