### ISSUE TITLE
Repo examples only sampling glycine

### ISSUE THREAD

**Issue by michael1788** [RosettaCommons/RFdiffusion#28]
Hey! Thanks for sharing this :)
I just had the following problem—maybe I'm doing something wrong on my end—but by trying both (i) RFdiffusion/examples/design_motifscaffolding.sh and (ii) RFdiffusion/examples/design_unconditional.sh, the randomly sampled ranges only contain Gs (e.g., for the motif example: "GGGGGGGGGGGGGGGGGGEVNKIKSALLSTNKAVVSLGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG")

**Comment by roccomoretti** [comment]
RFDiffusion by itself only produces backbone structures. If you're looking to find sidechain identities, you would want to use a method which places sidechains on a given backbone. -- I'd probably recommend [ProteinMPNN](https://github.com/dauparas/ProteinMPNN) for that.

**Comment by michael1788** [comment]
Oh, my bad. Thanks
