### ISSUE TITLE
Enforcing constraints on generated design

### ISSUE THREAD

**Issue by arutik** [RosettaCommons/RFdiffusion#302]
Hi,

How can I enforce constraints (i. e. I only want amino acids X,Y or Z in position 1; only X in position 2 etc.) onto the generated designs please? Is it supposed to be specified for RFdiffusion or downstream for sequence generation using proteinMPNN?

Thank you,
Anna Arutyunyan

**Comment by roccomoretti** [comment]
RFDiffusion doesn't generate amino acid sequences. It only builds new backbones. To specify sequence constraints when generating, you're best to look at the downstream sequence prediction machinery (e.g. ProteinMPNN).

That said, there is a sequence/structure relation, and the sort of backbone you'll generate can be affected by the type(s) of amino acid you're expecting at that position. There is some support for this, but I don't know how well that can be controlled for _de novo_ diffusion. (It's not a common use case.)

There is such control for partial diffusion, though. See the examples `design_partialdiffusion_withseq.sh` and `design_partialdiffusion_multipleseq.sh`. One approach you might try would be to run _de novo_ diffusion, apply your sequence (with ProteinMPNN or some other method), then re-diffuse with partial diffusion. With an a large `diffuser.partial_T`, it should be close to what you'd see with a `de novo` diffusion. (Though you'll probably want to run things independently on multiple outputs from the _de novo_ diffusion step.)

**Comment by arutik** [comment]
Thank you very much for your prompt response! 
Will try your suggestions 👍
