### ISSUE TITLE
Handling of non natural amino acids (Colab notebook version)

### ISSUE THREAD

**Issue by rche54** [RosettaCommons/RFdiffusion#36]
On the Colab notebook I am using as a template for binder generation the mirror image of a naturally occurring protein (uploaded pdb file). The generation of the poly glycine backbone works well but when this input is used for protein MPNN and Alphafold evaluation the outputs alter the stereochemistry of the input protein back to the natural enantiomer. It's not clear whether this is happening at the protein MPNN step or whether this is a step taken by Alphafold. Is there a way to discern whether Protein MPNN is assigning side chains based the mirror image protein input (or whether Protein MPNN reverts the stereochemistry)?

**Comment by joewatchwell** [comment]
I don't think AF2 is able to predict mirror-image proteins sadly (Gram Schmidt and the FAPE loss means mirror image proteins are seen as different to normal proteins).
