### ISSUE TITLE
ModuleNotFoundError: No module named 'rfdiffusion'

### ISSUE THREAD

**Issue by bwllc** [RosettaCommons/RFdiffusion#38]
Thanks so much to the RosettaCommons team for open-sourcing RFdiffusion!  I'm looking forward to getting started.

Unfortunately, something appears to have gone wrong with the folder organization of my installation.  I'm trying to execute the first example in the README, generating unconstrained backbones with 150 residues.  Here is my attempt to execute, and my output:

```
(SE3nv) john@john-Desktop:~/RFdiffusion$ ./scripts/run_inference.py 'contigmap.contigs=[150-150]' inference.output_prefix=test_outputs/test inference.num_designs=10
Traceback (most recent call last):
  File "/home/john/RFdiffusion/./scripts/run_inference.py", line 24, in <module>
    from rfdiffusion.util import writepdb_multi, writepdb
ModuleNotFoundError: No module named 'rfdiffusion'
```

So `run_inference.py` is being found -- but it's looking for the `util.py` file somewhere other than where it is, which is `/home/john/RFdiffusion/rfdiffusion`.

I know how to reorganize Python folders and/or to provide a folder link, to hack my way around this problem, but I'm concerned that I would cause other problems by doing so.

Please advise, thanks.

**Comment by bwllc** [comment]
Following up:

In order to try to move forward, I added a link to ../rfdiffusion into the scripts folder.  This cleared the above error, but generated a new error.  Since all I have done is to kick the can down the road a bit, I will be removing that link.

```
(SE3nv) john@john-Desktop:~/RFdiffusion$ ./scripts/run_inference.py 'contigmap.contigs=[150-150]' inference.output_prefix=test_outputs/test inference.num_designs=4
Traceback (most recent call last):
  File "/home/john/RFdiffusion/./scripts/run_inference.py", line 25, in <module>
    from rfdiffusion.inference import utils as iu
  File "/home/john/RFdiffusion/scripts/rfdiffusion/inference/utils.py", line 6, in <module>
    from rfdiffusion.diffusion import get_beta_schedule
  File "/home/john/RFdiffusion/scripts/rfdiffusion/diffusion.py", line 12, in <module>
    from rfdiffusion.util_module import ComputeAllAtomCoords
  File "/home/john/RFdiffusion/scripts/rfdiffusion/util_module.py", line 5, in <module>
    from opt_einsum import contract as einsum
ModuleNotFoundError: No module named 'opt_einsum'
```

Here's my RFdiffusion base folder organization.  It looks like an accurate clone of the git repo to me (minus the docker folder, which I think I don't need as I'm using miniconda):

```
(SE3nv) john@john-Desktop:~/RFdiffusion$ ls
config   env            helper_scripts  LICENSE  README.md    scripts
docker  examples  img                  models       rfdiffusion         setup.py
```

Still, based on the errors, I believe that my folder organization does not match what the tutorial expects.  Please help me to understand what the correct folder hierarchy should be.  If you see can any disagreements, I will correct them.

Thanks.

**Comment by bwllc** [comment]
**Followup:**
It turns out I had the CUDA compatibility problems which were described in Issue #14.  Using one of the alternate YAML configuration files provided in that discussion corrected my problem.  I'm closing this issue.

**Comment by fsmalik** [comment]
I get the same error. This one is new - the whole environment issue I've dealt with (many times). Any idea what's causing this? I've tried moving things around, but still nothing.

**Comment by fsmalik** [comment]
I get the hunch that something's been installed in the wrong place wrong time from having to jump hoops for installing cuda version of things in the environment.

**Comment by Jorge-GonzalezH** [comment]
I have this error : 

RuntimeError: NVTX functions not installed. Are you sure you have a CUDA build?

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

**Does anyone have a clue how to solve it?**

**Comment by roccomoretti** [comment]
@Jorge-GonzalezH It's best to open a new issue if your problem is different (e.g. gives a different error message). There's no real harm in opening a new issue even if the error message is the same. -- That said, your error is related to proper installation of CUDA/GPU versions of software. If you [search issues for NVTX](https://github.com/RosettaCommons/RFdiffusion/issues?q=is%3Aissue+NVTX+), there are a number of others with similar error messages, and a solution for you may be included there.
