### ISSUE TITLE
How to fix part of sequence in binder design or provide hotspot in partial denoising?

### ISSUE THREAD

**Issue by ShuhaoGithub** [RosettaCommons/RFdiffusion#42]
Hello authors,

Thank you for providing this fantastic code for protein design! I was wondering if there is a smart way to incorporate some sequence information in binder design process or add a hot spot potential in partial denoise process. I was trying to optimize a binder. If I use the partial denoise pipeline, I cannot define the hotspot; If I use the binder design pipeline, I cannot fix the part of the sequence of interest. I assume there should be a way to combine both features because they are simply two different potential functions. Could you let me know if that's possible or some clue for me to implement this feature? Thank you very much!

Best,
Shuhao

**Comment by joewatchwell** [comment]
This is a good point - we'll look to implement this soon!

**Comment by Joseph-Vineland** [comment]
Has this been fixed yet?  I still can't use the 'contigmap.provide_seq' argument and the the 'ppi.hotspot_res' argument at the same time.  It always throws an error.  Examples are below.  If I don't choose hotspots it warns me that the model was trainged with hotpots and should be used accordingly.  

"WARNING: you're using a model trained on complexes and hotspot residues, without specifying hotspots.                         If you're doing monomer diffusion this is fine"  I'm doing binder-target partial diffusion though.

These commands don't work:

../scripts/run_inference.py inference.output_prefix=example_outputs/design_partialdiffusion_peptidewithsequence inference.input_pdb=input_pdbs/peptide_complex_ideal_helix.pdb 'contigmap.contigs=["172-172/0 34-34"]' diffuser.partial_T=10 inference.num_designs=10 'contigmap.provide_seq=[172-205]' 'ppi.hotspot_res=[111,144]'

../scripts/run_inference.py inference.output_prefix=example_outputs/design_partialdiffusion_peptidewithsequence inference.input_pdb=input_pdbs/peptide_complex_ideal_helix.pdb 'contigmap.contigs=["172-172/0 34-34"]' diffuser.partial_T=10 inference.num_designs=10 'contigmap.provide_seq=[172-205]' 'ppi.hotspot_res=[A111,A144]'

**Comment by markf94** [comment]
+1 - facing the same issues as @Joseph-Vineland and @ShuhaoGithub
