### ISSUE TITLE
Enable discussions in Github repo

### ISSUE THREAD

**Issue by akulmehta** [RosettaCommons/RFdiffusion#49]
Really amazing work firstly. I had a suggestion to enable discussion in the Github repository so that interested users could discuss about potential uses etc. https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/enabling-or-disabling-github-discussions-for-a-repository

**Comment by joewatchwell** [comment]
Great idea - we'll set this up ASAP!
