### ISSUE TITLE
Is it possible to use RFDiffusion for generating small molecule binders ?

### ISSUE THREAD

**Issue by hima111997** [RosettaCommons/RFdiffusion#53]
Hi

Thank you for providing this excellent tool for protein design.
I have a question. Is it possible to use RFDiffusion for generating small molecule-binding protein assuming that there is a designed pocket (only separate amino acids that have good interactions with the molecule)?

Thanks

**Comment by roccomoretti** [comment]
I'd recommend taking a look at the "enzyme design" examples. (e.g. the "Scaffolding enzyme active sites" section and Figure S5 and associated in the paper, and design_enzyme.sh in the examples directory.) Enzyme design is basically just small molecule binding design, but where the small molecule is a transition state. The techniques used there should also be applicable when the molecule is a stable one.

Note that you'll likely indeed want to have pre-identified binding motifs (binding residues with the correct geometry) which RFDiffusion can scaffold around, but that's a technique that's used heavily in small molecule binding protein design. (e.g. https://doi.org/10.1038/nature12443)
