### ISSUE TITLE
Colab Error [Errno 2] No such file or directory: 'outputs/traj/test_0_pX0_traj.pdb'

### ISSUE THREAD

**Issue by remybonnav** [RosettaCommons/RFdiffusion#54]
Today  I got the error in google colab when running a diffusion. last Friday it was working well.

[Errno 2] No such file or directory: 'outputs/traj/test_0_pX0_traj.pdb' w

**Comment by sokrypton** [comment]
Can you provide more details how you got this error? Also, the link to notebook you are using.
The default settings don't have this error.

**Comment by remybonnav** [comment]
My bad, I was using binder mode but forgot the ":" between chain and number (eg: I wote A50 instead of A:50)

**Comment by remybonnav** [comment]
Actually, the issue was due to having space between hotspot "A12, A36, A56" but works if using "A12,A36,A56"

**Comment by sokrypton** [comment]
Thanks! I'll add some space filtering to avoid this issue.
