### ISSUE TITLE
Extend N-terminus with a helical bundle structure

### ISSUE THREAD

**Issue by gha2012** [RosettaCommons/RFdiffusion#55]
Hi,
thank you for providing this code and the examples! Suppose I have a .pdb file of a protein with a long alpha helix at the N-terminus. Is it possible to extend this helix by a helix bundle, i.e. to generate an N-terminal fusion of a three helix bundle to my target protein? The helical bundles that are generated by the design_ppi script would be perfect.

**Comment by joewatchwell** [comment]
Yes! You should be able to do this by building a block-adjacency matrix input specifying this - Sergey's colab notebook has a great GUI for constructing these :)
