### ISSUE TITLE
Problems with using Complex_beta_ckpt.pt

### ISSUE THREAD

**Issue by Lyang556** [RosettaCommons/RFdiffusion#6]
Hi, RF diffusion team

This is a great work.

I am trying to make a binder to a beta sheet, and i tried using Complex_beta_ckpt.pt.

The results showed that the binder sequences were GGGGGGGG....

What should i do to solve this problems? 

My code is python ${script_path}/run_inference.py inference.output_prefix=out/design_ppi inference.input_pdb=input/target.pdb 'contigmap.contigs=[C1-62/0 50-79]' 'ppi.hotspot_res=[C2,C3,C14,C15,C16,C17,C18,C20]' inference.ckpt_override_path=${script_path}/models/Complex_beta_ckpt.pt inference.num_designs=10 denoiser.noise_scale_ca=0 denoiser.noise_scale_frame=0

Thank you.

**Comment by youngh81** [comment]
I think it could be the backbone!

**Comment by Lyang556** [comment]
Thanks for the comment! Absolutely amazing work from the team and thanks a lot for getting back!
