### ISSUE TITLE
Colabfold implementation

### ISSUE THREAD

**Issue by ttessie2** [RosettaCommons/RFdiffusion#63]
I've been using RFdiffusion on colab pro for a few weeks now, using Google's GPUs. Realistically, we want to generate hundreds to thousands of designs and then filter through these. How is this supposed to be implemented when the max I can do is 32 designs in colab pro? I'm not sure how running RFdiffusion locally on my own GPU (RTX3060) would work out, any thoughts? I have never done any serious computing since I'm mostly at the bench, so technically I am very naive. 

Thanks for RFdiffusion!

**Comment by joewatchwell** [comment]
No problem! We're glad you're using it :)
Generating thousands of designs is indeed a challenge without access to compute clusters. If your designs aren't too long in length, you should be able to generate a good number even on a single gpu (at a guess, I would imagine you could probably make around 500-1000 designs/24h at about 150 amino acids in length). So maybe just cranking the single gpu is the best approach for now. Alternatively, if your lab has money, you might be able to buy some compute on AWS etc. Finally, if things are looking interesting etc there might be people here at the IPD interested in collaborating/helping out with compute etc :)
