### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'outputs/traj/test_0_pX0_traj.pdb'

### ISSUE THREAD

**Issue by gezmi** [RosettaCommons/RFdiffusion#77]
Hi,

For the past week, whenever I am trying to run partial diffusion, I get the following error: 
FileNotFoundError: [Errno 2] No such file or directory: 'outputs/traj/test_0_pX0_traj.pdb'

![image](https://github.com/RosettaCommons/RFdiffusion/assets/13509667/7100f823-9db0-4519-9521-967d574ff2a5)

I attached a picture with my input. After settings those, I have only did Runtime->Run All.

Could you help me to solve this problem?

Thank you!

**Comment by sokrypton** [comment]
in pdb 1ycr, chain B does not have position 9:
<img width="686" alt="image" src="https://github.com/RosettaCommons/RFdiffusion/assets/4187522/491d0a63-26ad-42af-bae3-0ca24abe88e2">
