### ISSUE TITLE
I was installing RFdiffusion in my Linux system but ran into the following error.

### ISSUE THREAD

**Issue by sHr3y4s1** [RosettaCommons/RFdiffusion#78]
I was installing RFdiffusion in my Linux system but ran into the following error.
![Capture](https://github.com/RosettaCommons/RFdiffusion/assets/70771390/94128743-b801-4d4b-b403-2bbebc989e2d)
I have tried updating the pip and pytorch versions but nothing seems to work. Any help would be appreciated!

_Originally posted by @sHr3y4s1 in https://github.com/RosettaCommons/RFdiffusion/discussions/64_

**Comment by roccomoretti** [comment]
The se3-transformer should have been installed in the previous step. (The `python setup.py install` run in the env/SE3Transformer directory: https://github.com/RosettaCommons/RFdiffusion#conda-install-se3-transformer)  Was there any error running that step? If you open up a python terminal, can you do an `import se3_transformer` without error?

**Comment by sHr3y4s1** [comment]
I tried import se3_transformer but it seems that it wasn't installed in the previous step.
![Capture](https://github.com/RosettaCommons/RFdiffusion/assets/70771390/6b9bb042-7211-47ca-a515-1f6ae03f72f7)
I will try to install it again. Thank you for your help!
