### ISSUE TITLE
Doubts regarding binder design results

### ISSUE THREAD

**Issue by shashkat** [RosettaCommons/RFdiffusion#85]
Hey there! firstly thanks a lot for making such an awesome tool and making it open for usage by the scientific community! So I want to design binder for my protein, but initially am just giving a try to the sample protein mentioned in the repo: 5tpn

I have been wondering about the following (they are probably naive issues but if someone could clarify them, I shall be highly grateful):

I ran this command after following the steps to set up the docker container: 

```
docker run -it --rm \
  -v $HOME/models:$HOME/models \
  -v $HOME/inputs:$HOME/inputs \
  -v $HOME/outputs:$HOME/outputs \
  rfdiffusion \
  inference.output_prefix=$HOME/outputs/motifscaffolding \
  inference.model_directory_path=$HOME/models \
  inference.input_pdb=$HOME/inputs/5TPN.pdb \
  inference.num_designs=3 \
  'contigmap.contigs=[10-40/A163-181/10-40]'
```

- for the results from rfdiffusion, it is stated that all the residues will be glycine, but for me, they are the same residues as 5tpn in the specified range (A163-181), flanked by some glycine residues on each side. Is this the correct behavior?
- I followed the dl_binder_design repo (https://github.com/nrbennet/dl_binder_design) as the next step. According to what I read, I expected it to keep the structure of the binder same, and just modify its sequence so that the new sequence would now actually fold to the original structure (which was determined by rfdiffusion). However, I observe that the sequence has remained the same (5tpn sequence from 163-181, flanked by glycines on both side) and the structure has changed after running Proteinmpnn on the rfdiffusion results. I used this command: `<base_dir>/mpnn_fr/dl_interface_design.py -silent my_designs.silent`
- Also, I want to show the created binder beside the protein for which it is designed (5tpn in this case), showing their interaction as shown in the paper. however, when i import them both together in say, pymol, they are at a distance. Why is this so?

Any help will be greatly appreciated!
Thank You!

**Comment by joewatchwell** [comment]
Hello! So this protocol you've run isn't doing binder design, it's actually doing motif scaffolding. What you're asking for in the contig is: "Add 10-40 (randomly sampled) residues upstream of residues A163-181 of 5tpn, followed by 10-40 (again randomly sampled) residues downstream of the 5tpn motif". Therefore, you expect an output where the motif is flanked by two glycine regions (all on one chain).
I'd take a look at the binder design examples instead. They will output a completely de novo binder on chain A, and the target on chain B. These will then plug into the downstream ProteinMPNN/AF2 scripts etc.
Good luck!
