### ISSUE TITLE
Using non-protein targets for binder design

### ISSUE THREAD

**Issue by mdpoleto** [RosettaCommons/RFdiffusion#86]
Hi,

I understand RosettaFold has been extended to deal with nucleic-acid and nucleic-acid protein complexes, but what is the current status on RFdiffusion being able to deal with non-protein (not only nucleic-acids, but also carbohydrates, etc) targets when designing binders? Sorry if the question is out of place, but I could not find clear information on latest papers or issues raised here.

**Comment by joewatchwell** [comment]
Currently, RFdiffusion only deals with protein atoms, but we're working on extending it! The code isn't currently available though.
